### ISSUE TITLE
Doesn't work unless connected to destination

### ISSUE THREAD

**Issue by dbkaplun** [mohayonao/stereo-analyser-node#7]
See here: https://github.com/dbkaplun/visual-experiments/blob/713b4781e857c1aa3de836e45649df4fc580b3e6/src/index.jsx#L29

If I change `this.analyserStereo` to `this.source` the Float32Arrays [here](https://github.com/dbkaplun/visual-experiments/blob/713b4781e857c1aa3de836e45649df4fc580b3e6/src/index.jsx#L71-L72) are empty.

**Comment by mohayonao** [comment]
Okay, I fixed this issue.
It is maybe chrome (webkit/blink) 's bug?

https://jsfiddle.net/mohayonao/pv0Lqxas/2/

<img width="564" alt="analyser-node" src="https://cloud.githubusercontent.com/assets/158075/20644443/c1405fb2-b477-11e6-8ac5-222aab1ff6c7.png">

**Comment by dbkaplun** [comment]
Confirmed, thanks!
